kasir/urls.py
from django.urls import path
from kasir.views import *

app_name = 'kasir'

urlpatterns= [
   path('', show_kasir, name="show_kasir"),
   path('json/', show_json, name="show_json"),
   path('login/', login_user, name="login_user"),
   path('register/', register, name="register"),
   path('logout/', logout_user, name="logout"),
   path('create/', create_bill_ajax, name="create_bill_ajax" ),
   path('payment/<int:id>', payment_bill_ajax, name="payment_bill_ajax"),
   path('delete/<int:id>', delete_bill_ajax, name="delete_bill_ajax" ),
   path('no_login/', no_login, name="no_login"),
   path('add/', flutter_add, name='flutter_add'),
   path('delete_flutter/<int:pk>/', delete_flutter, name='delete_flutter'),
   path('payment_flutter/<int:pk>/', payment_bill_flutter, name='payment_bill_flutter'),
]

 

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('childcare/', include('childcare.urls')),
    path('kasir/', include('kasir.urls')),
    path('vaksin/', include('vaksin.urls')),
    path('checkup/',include('checkup.urls')),
    path('apotek/',include('apotek.urls'))
]

vaksin/urls.py
from django.urls import path
from vaksin.views import show_vaksin_info, add_vaksin, show_json, login_user, register, logout_user, show_added_vaksin, delete_vaksin
from vaksin.views import change_dose, homepage, flutter_add, flutter_edit_dose

app_name = 'vaksin'

urlpatterns = [
    path('', show_vaksin_info, name='show_vaksin_info'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('json/', show_json, name='show_json'),
    path('json1/', show_added_vaksin, name='show_added_vaksin'),
    path('add/', add_vaksin, name='add_vaksin'),
    path('change/', change_dose, name='change_dose'),
    path('delete-vaksin/<int:id>', delete_vaksin, name='delete_vaksin'),
    path('no-login/', homepage, name='homepage'),
    path('flutter-add/', flutter_add, name='flutter_add'),
    path('flutter-edit/', flutter_edit_dose, name='flutter_edit'),
]

vaksin/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

# class User(AbstractUser):
#     is_doctor = models.BooleanField('Is doctor', default = False)
#     is_patient = models.BooleanField('Is patient', default = False)

class Vaksin(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    name = models.CharField(max_length=100)
    side_effect = models.CharField(max_length=255)
    dose = models.FloatField()
    stock = models.IntegerField()

vaksin/forms.py
from django import forms
from vaksin.models import Vaksin, User
from django.contrib.auth.forms import UserCreationForm

class VaksinForm(forms.ModelForm):
    class Meta:
        model = Vaksin
        # fields = '__all__'
        exclude = ('user',)

class LoginForm(forms.Form):
    username = forms.CharField(
        widget = forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    password = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )

class RegisterForm(forms.Form):
    username = forms.CharField(
        widget = forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    password1 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    password2 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = User
        fields = {'username', 'password1','password2', 'is_doctor', 'is_patient'}

vaksin/views.py
from django.shortcuts import render, redirect

# Create your views here.
import datetime
from vaksin.models import Vaksin
from vaksin.forms import VaksinForm, LoginForm, RegisterForm
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.core import serializers
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.http.response import JsonResponse
import json

@login_required(login_url='/vaksin/no-login/')
def show_vaksin_info(request):
    form = VaksinForm()
    context = {
        'register_status': 'hidden',
        'login_status': 'hidden',
        'form': form,
        'path': 'vaksin'
        }
    return render(request, "doctor_views.html", context)

def homepage(request):
    context = {
        'logout_status': 'hidden',
        'path': 'vaksin'
    }
    return render(request, "default_views.html", context)

def show_added_vaksin(request):
    vaksin_data = Vaksin.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", vaksin_data))

def show_json(request):
    vaksin_data = Vaksin.objects.all()
    return HttpResponse(serializers.serialize("json", vaksin_data))

@login_required(login_url='/vaksin/login/')
def add_vaksin(request):
    if request.method == "POST":
        form = VaksinForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = User.objects.get(username=request.user.username)
            obj.save()
            return HttpResponse(b"CREATED", status=201)
            
    return HttpResponseNotFound()

@login_required(login_url='/vaksin/login/')
def delete_vaksin(request, id):
    vaksin = Vaksin.objects.get(pk=id)
    vaksin.delete()

    return HttpResponse(b"DELETED", status=204)

@login_required(login_url='/vaksin/login/')
def change_dose(request):
    if request.method=="POST":
        new_dose = request.POST.get("vaksin_dose")
        vaksin_id = request.POST.get("vaksin_option")
        vaksin = Vaksin.objects.get(pk=vaksin_id)
        vaksin.dose = float(new_dose)
        vaksin.save()
        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('vaksin:login')
    
    context = {
        'form':form,
        'path': 'vaksin',
        'logout_status': 'hidden'
        }
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("vaksin:show_vaksin_info")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {
        'path': 'vaksin',
        'logout_status': 'hidden'
    }
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('vaksin:login'))
    response.delete_cookie('last_login')
    return response

@csrf_exempt
def flutter_add(request):
    data = json.loads(request.body)
    name = data['name']
    sideEffect = data['sideEffect']
    dose = float(data['dose'])
    stock = int(data['stock'])
    user = User.objects.get(username=request.user.username)
    if request.method == 'POST':
        vaksin = Vaksin(user=user, name=name, side_effect=sideEffect, dose=dose, stock=stock)
        vaksin.save()
        return JsonResponse({"message": "vaksin berhasil ditambahkan", "status":200}, status=200)

    return JsonResponse({"message": "wrong method", "status":502}, status = 502)

@csrf_exempt
def flutter_edit_dose(request):
    data = json.loads(request.body)
    name = data['name']
    dose = float(data['dose'])
    if request.method == 'POST':
        vaksin = Vaksin.objects.get(name=name)
        vaksin.dose = dose
        vaksin.save()
        return JsonResponse({"message": "dosis berhasil diubah", "status":200}, status=200)

    return JsonResponse({"message": "wrong method", "status":502}, status = 502)

vaksin/templates/default_views.html
{% extends 'base.html' %}

    {% block content %}
    <div class="bg-[url('../../static/images/vaksin.png')] color-white bg-fixed bg-no-repeat w-full bg-cover bg-center">
        <div class="bg-[#00000066] font-bold text-center text-5xl py-40 text-white">Vaksin</div>
      </div>
    <div class="bg-stone-800 py-10">
        <h1 class="font-bold text-5xl text-white text-center pb-8">Guidelines</h1>
        <div class="py-5 mb-10">
            <p class="text-white text-xl text-center pb-10">Please Login first to see the full feature</p>
            <center>
                <form action = "{% url 'vaksin:login' %}">
                    <button type="submit" id="user_button" class="text-white text-xl bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-5 mb-8 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Login</button>
                </form>
            </center>
        </div>
    </div>
    {% endblock content %}

vaksin/templates/doctor_views.html
{% extends 'base.html' %}

    {% block content %}

    <div class="bg-[url('../../static/images/vaksin.png')] color-white bg-fixed bg-no-repeat w-full bg-cover bg-center">
      <div class="bg-[#00000066] font-bold text-center text-5xl py-40 text-white">Vaksin</div>
    </div>
    <div class="bg-stone-800 py-10">
        <h1 class="font-bold text-5xl text-white text-center pb-8">Guidelines</h1>
        <div class="py-5 mb-10">
          <li class="text-white mx-20 mb-2 text-xl">"Tambah Vaksin" can be used to add a new type of vaccine to the database</li>
          <li class="text-white mx-20 mb-2 text-xl">"Edit Dosis" can be used to re-configure the dose of a vaccine from the database</li>
          <li class="text-white mx-20 mb-2 text-xl">"Cek Stok" can be used to see the stock of a vaccine from the database</li>
          <li class="text-white mx-20 mb-2 text-xl">"Lihat Vaksin User" can be used to see the list of vaccines that you have added to the database</li>
          <li class="text-white mx-20 mb-2 text-xl">"Kembali" can be used to navigate to the initial webpage</li>
        </div>
    <center>
        <hr class="mx-14 text-white border-2"></hr>
        <h1 class="font-bold text-5xl text-white pt-10 pb-3">Data Vaksin MedStem</h1>
        <h4>Username: {{user}}</h4>
        <button type="button" id="user_button" onclick="userVaksin()" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-5 mb-8 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Lihat Vaksin User</button>
        <button type="button" id="kembali" onclick="refreshVaksin()" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-5 mb-8 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Kembali</button>
        <table class="mb-12 border-slate-500 border-2 border-collapse">
          <thead id="table_header" class="text-slate-400 bg-gray-700 border-2">
            <!-- <tr>
            <th class="px-10 py-2 text-center border border-slate-500">Nama Vaksin</th>
            <th class="px-10 py-2 text-center border border-slate-500">Efek Samping</th>
            <th class="px-10 py-2 text-center border border-slate-500">Dosis Vaksin(mg)</th>
            <th class="px-10 py-2 text-center border border-slate-500">Hapus Vaksin</th>
            </tr> -->
          </thead>
          <tbody id="data_vaksin" class="text-zinc-400 border-2 bg-zinc-800"></tbody>
        </table>
    
    <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-5 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">Tambah Vaksin</button>
    <button type="button" onclick="vaksinList()" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-5 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" data-bs-toggle="modal" data-bs-target="#edit_dosis" data-bs-whatever="@getbootstrap">Edit Dosis</button>
    <button type="button" onclick="vaksinList1()" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-5 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" data-bs-toggle="modal" data-bs-target="#check_stock" data-bs-whatever="@getbootstrap">Cek Stok</button>
  </center>


      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content bg-slate-700">
            <div class="modal-header">
              <h1 class="modal-title fs-5 text-white" id="exampleModalLabel">Formulir Tambah Vaksin</h1>
              <button type="button" class="btn-close text-white bg-gray-700" data-bs-dismiss="modal" aria-label="Close" value="X"></button>
            </div>
            <div class="modal-body">
              <form id="form_vaksin" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                  {% for field in form %}
                    <div class="grid grid-cols-3">
                        <div class="col-span-1 text-white">{{field.label}}</div>
                        <div class="col-span-2 py-2">{{field}}</div>
                    </div>
                  {% endfor %}
                </div>
              </form>
            </div>
              <div class="modal-footer">
              <button type="button" class="btn btn-secondary text-white-center bg-red-700" data-bs-dismiss="modal">Close</button>
              <button type="button" onclick="addVaksin()" class="btn btn-primary text-white-center bg-blue-700" id="add_button" data-bs-dismiss="modal">Tambah</button>
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="edit_dosis" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content bg-slate-700">
            <div class="modal-header">
              <h1 class="modal-title fs-5 text-white" id="exampleModalLabel">Edit Dosis</h1>
              <button type="button" class="btn-close text-white bg-gray-700" data-bs-dismiss="modal" aria-label="Close">X</button>
            </div>
            <div class="modal-body">
              <form id="edit_dose" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                  <label for="dosis" class="col-form-label text-white">Dosis baru</label>
                  <input type="number" class="form-control bg-slate-300" id="field_dose" name="vaksin_dose">
                </div>
                <div class="mb-3">
                  <label for="vaksin" class="col-form-label text-white">Pilih Vaksin</label>
                  <br>
                  <select for="vaksin_option" id="select_dropdown" name="vaksin_option" class="px-6 border-1 bg-slate-300 border-grey-500"></select>
                </div>
              </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary text-white-center bg-red-700" data-bs-dismiss="modal">Close</button>
              <button type="button"  onclick="editDose()" class="btn btn-primary text-white-center bg-blue-700" id="edit_button" data-bs-dismiss="modal">Edit</button>
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="check_stock" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content bg-slate-700">
            <div class="modal-header">
              <h1 class="modal-title fs-5 text-white" id="exampleModalLabel">Cek Stok Vaksin</h1>
              <button type="button" class="btn-close text-white bg-gray-700" data-bs-dismiss="modal" aria-label="Close" value="X"></button>
            </div>
            <div class="modal-body">
              <div class="mb-3">
                <form>
                  <label for="vaksin" class="col-form-label text-left text-white">Pilih Vaksin</label>
                  <br>
                  <select for="vaksin_option" id="select_dropdown1" name="vaksin_option" class="py-1 px-4 text-left bg-slate-300">
                    
                  </select>
                  <br>
                </form>
              </div>
              <div class="mb-3">
                <h3 id="text_stock"></h3>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary text-white-center bg-red-700" data-bs-dismiss="modal">Close</button>
              <button type="button" onclick="checkStock()" class="btn btn-primary text-white-center bg-blue-700" id="check_button">Cek</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% load static %}
    <script src="{% static 'js/vaksin/vaksin_ajax.js' %}"></script>
    <script>
        refreshVaksin()
    </script>

    {% endblock content %}

vaksin/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1 id="head" class="text-center font-bold text-black-600">Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table id="table-login">
            <tr>
                <td id="login-text">Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td id="login-text">Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>
        </table>
        <br>
             <td><input class="btn border-blue-500 text-blue-500" type="submit" value="Login" id="button-login"></td>
         </br>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
    <br></br>
    Belum mempunyai akun? <a href="{% url 'vaksin:register' %}">Buat Akun</a>

</div>

{% endblock content %}

vaksin/templates/modals.html
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">Tambah Vaksin</button>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Formulir Tambah Vaksin</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="formtask">
          {% csrf_token %}
          <div class="mb-3">
            <table>
              {{ form.as_table }}
            </table>
          </div>
        </form>
      </div>
        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="addtaskbutton" data-bs-dismiss="modal">Tambah</button>
      </div>
    </div>
  </div>
</div>

vaksin/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1 id="head">Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
            </table>  
            <br>
                <a id ="button-register" href="{% url 'vaksin:login' %}">Kembali</a>
                <td><input type="submit" name="submit" value="Daftar" id="button-register"/></td>  
            </br>
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}